name: Tests
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DFX_VERSION: 0.24.2
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache cargo build
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: fmt
        run: cargo fmt -v -- --check
      - name: lint
        run: cargo clippy --tests -- -D clippy::all
      - name: Install dfx
        uses: dfinity/setup-dfx@e50c04f104ee4285ec010f10609483cf41e4d365 # main
        with:
          dfx-version: "${{ env.DFX_VERSION }}"
      - name: Run e2e tests against replica
        run: |
          echo '{}' > dfx.json
          dfx start --background --clean
          set -ex
          target/debug/ic-repl examples/install.sh
          target/debug/ic-repl examples/func.sh
          dfx stop
      - name: Run e2e tests against PocketIC
        run: |
          echo '{}' > dfx.json
          dfx start --background --clean --pocketic
          set -ex
          target/debug/ic-repl examples/install.sh
          target/debug/ic-repl examples/func.sh
          dfx stop
