name: Release
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Release for ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-20.04
            name: linux64
            artifact_name: target/release/ic-repl
            asset_name: ic-repl-linux64
          - os: macos-latest
            name: macos
            artifact_name: target/release/ic-repl
            asset_name: ic-repl-macos
          - os: ubuntu-latest
            name: arm
            artifact_name: target/arm-unknown-linux-gnueabihf/release/ic-repl
            asset_name: ic-repl-arm32
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        if: matrix.name != 'arm'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install stable ARM toolchain
        if: matrix.name == 'arm'
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: arm-unknown-linux-gnueabihf
      - name: Build
        if: matrix.name != 'arm'
        run: cargo build --release --locked
      - name: Cross build
        if: matrix.name == 'arm'
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target arm-unknown-linux-gnueabihf --release --locked
      - name: 'Upload assets'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.artifact_name }}
          retention-days: 3
  test:
    needs: build
    name: Test for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            asset_name: ic-repl-linux64
          - os: ubuntu-20.04
            asset_name: ic-repl-linux64
          - os: macos-13
            asset_name: ic-repl-macos
          - os: macos-12
            asset_name: ic-repl-macos
          - os: macos-11
            asset_name: ic-repl-macos
    steps:
      - name: Get executable
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
      - name: Executable runs
        run: |
          chmod +x ic-repl
          ./ic-repl --version
  publish:
    needs: test
    name: Publish ${{ matrix.asset_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - asset_name: ic-repl-linux64
          - asset_name: ic-repl-arm32
          - asset_name: ic-repl-macos
    runs-on: ubuntu-latest
    steps:
      - name: Get executable
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ic-repl
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
